import "./globals.css";
import { bentonSansPro } from "./fonts";

export const metadata = {
  title: "S-Class | Standard Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bentonSansPro.variable}`}>
      <body className={`${bentonSansPro.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
